version: '3'
services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./
    environment: 
      - PYTHONUNBUFFERED=1
    ports: 
      - "8000:8000"
    volumes: 
      - "./images:/images"